package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea", catalog = "commonweal")
public class Idea implements java.io.Serializable {

	private Integer ideaId;
	private State state;
	private Integer personId ;
	

	private String ideaContent;
	private String personEmail;
	private Date ideaCreateDate;

	public Idea() {
	}

	public Idea(State state, Integer personId, String ideaContent,
			String personEmail, Date ideaCreateDate) {
		this.personId=personId;
		this.state = state;
		this.ideaContent = ideaContent;
		this.personEmail = personEmail;
		this.ideaCreateDate = ideaCreateDate;
	}
	@Column(name ="ideaPersonId")
	public Integer getPersonId() {
		return personId;
	}
	public void setPersonId(Integer personId) {
		this.personId = personId;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ideaId", unique = true, nullable = false)
	public Integer getIdeaId() {
		return this.ideaId;
	}

	public void setIdeaId(Integer ideaId) {
		this.ideaId = ideaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}


	@Column(name = "ideaContent", length = 50)
	public String getIdeaContent() {
		return this.ideaContent;
	}

	public void setIdeaContent(String ideaContent) {
		this.ideaContent = ideaContent;
	}

	@Column(name = "personEmail", length = 50)
	public String getPersonEmail() {
		return this.personEmail;
	}

	public void setPersonEmail(String personEmail) {
		this.personEmail = personEmail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ideaCreateDate", length = 19)
	public Date getIdeaCreateDate() {
		return this.ideaCreateDate;
	}

	public void setIdeaCreateDate(Date ideaCreateDate) {
		this.ideaCreateDate = ideaCreateDate;
	}

}
