package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Info generated by hbm2java
 */
@Entity
@Table(name = "info", catalog = "commonweal")
public class Info implements java.io.Serializable {

	private Integer infoId;
	private String infoContent;
	private Date infoCreateDate;

	public Info() {
	}

	public Info(String infoContent, Date infoCreateDate) {
		this.infoContent = infoContent;
		this.infoCreateDate = infoCreateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "infoId", unique = true, nullable = false)
	public Integer getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Integer infoId) {
		this.infoId = infoId;
	}

	@Column(name = "infoContent")
	public String getInfoContent() {
		return this.infoContent;
	}

	public void setInfoContent(String infoContent) {
		this.infoContent = infoContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "infoCreateDate", length = 19)
	public Date getInfoCreateDate() {
		return this.infoCreateDate;
	}

	public void setInfoCreateDate(Date infoCreateDate) {
		this.infoCreateDate = infoCreateDate;
	}

}
