package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Notice generated by hbm2java
 */
@Entity
@Table(name = "notice", catalog = "commonweal")
public class Notice implements java.io.Serializable {

	private Integer noticeId;
	private State state;
	private Type type;
	private Integer personId;
	@Column(name = "personId")
	public Integer getPersonId() {
		return personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	private Resource resource;
	private String noticeDetail;
	private String noticeTittle;

	private Integer noticeAging;
	private Date noticeCreateDate;

	public Notice() {
	}

	public Notice(Date noticeCreateDate) {
		this.noticeCreateDate = noticeCreateDate;
	}

	public Notice(State state, Type type, Integer personId, Resource resource,
			String noticeDetail, String noticeTittle,
			Integer noticeAging, Date noticeCreateDate) {
		this.state = state;
		this.type = type;
		this.personId = personId;
		this.resource = resource;
		this.noticeDetail = noticeDetail;
		this.noticeTittle = noticeTittle;
		
		this.noticeAging = noticeAging;
		this.noticeCreateDate = noticeCreateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "noticeId", unique = true, nullable = false)
	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stateId")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeId")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noticeImgId")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@Column(name = "noticeDetail")
	public String getNoticeDetail() {
		return this.noticeDetail;
	}

	public void setNoticeDetail(String noticeDetail) {
		this.noticeDetail = noticeDetail;
	}

	@Column(name = "noticeTittle", length = 50)
	public String getNoticeTittle() {
		return this.noticeTittle;
	}

	public void setNoticeTittle(String noticeTittle) {
		this.noticeTittle = noticeTittle;
	}

	@Column(name = "noticeAging")
	public Integer getNoticeAging() {
		return this.noticeAging;
	}

	public void setNoticeAging(Integer noticeAging) {
		this.noticeAging = noticeAging;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "noticeCreateDate", nullable = false, length = 19)
	public Date getNoticeCreateDate() {
		return this.noticeCreateDate;
	}

	public void setNoticeCreateDate(Date noticeCreateDate) {
		this.noticeCreateDate = noticeCreateDate;
	}

}
