package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "commonweal")
public class Resource implements java.io.Serializable {

	private Integer resourceId;
	private String resourcePath;
	private Type type;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "typeId")
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	private String resourceSource;
	


	public Resource() {
	}


	public Resource(Integer resourceId, String resourcePath, Type type,
			String resourceSource) {
		super();
		this.resourceId = resourceId;
		this.resourcePath = resourcePath;
		this.type = type;
		this.resourceSource = resourceSource;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resourceId", unique = true, nullable = false)
	public Integer getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "resourcePath", length = 100)
	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

	

	@Column(name = "resourceSource", length = 50)
	public String getResourceSource() {
		return this.resourceSource;
	}

	public void setResourceSource(String resourceSource) {
		this.resourceSource = resourceSource;
	}

	

}
