package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TableManage generated by hbm2java
 */
@Entity
@Table(name = "TableManage", catalog = "commonweal")
public class TableManage implements java.io.Serializable {

	private Integer tableId;
	private String tableNameZh;
	private String tableNameUk;
	public TableManage() {
	}

	public TableManage(String tableNameZh, String tableNameUk) {
		this.tableNameZh = tableNameZh;
		this.tableNameUk = tableNameUk;
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tableId", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@Column(name = "tableNameZH", nullable = false, length = 50)
	public String getTableNameZh() {
		return this.tableNameZh;
	}

	public void setTableNameZh(String tableNameZh) {
		this.tableNameZh = tableNameZh;
	}

	@Column(name = "tableNameUK", nullable = false, length = 50)
	public String getTableNameUk() {
		return this.tableNameUk;
	}

	public void setTableNameUk(String tableNameUk) {
		this.tableNameUk = tableNameUk;
	}



}
