package cn.tuyuan.commonweal.pojo;

// Generated 2017-12-26 15:38:16 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", catalog = "commonweal")
public class Type implements java.io.Serializable {

	private Integer typeId;
	private Integer tableId;
	

	@Column(name = "tableId")
	public Integer getTableId() {
		return tableId;
	}


	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	private String typeName;

	public Type() {
	}


	public Type(Integer typeId, Integer tableId, String typeName) {
		super();
		this.typeId = typeId;
		this.tableId = tableId;
		this.typeName = typeName;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "typeId", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		if(typeId<0){
			this.typeId = 12;
		}
		this.typeId=typeId;
	}

	@Column(name = "typeName", nullable = false, length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}


}
